# Generated by Django 2.2.12 on 2020-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0024_overview_adds_has_highlights.py'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewtab',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
