# Generated by Django 2.2.16 on 2021-10-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0003_auto_20210923_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Course is public and should be available on publisher spaces'),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='publisher_card_logo_url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='publisher_name',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
