# Generated by Django 2.2.16 on 2021-11-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0004_auto_20211027_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='days_to_unlock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='subsection_to_lock',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
