# Generated by Django 2.2.16 on 2021-11-29 11:31

from django.db import migrations


def create_default_space_and_organization(apps, schema_editor):
    default_space = 'ilmx'
    from ..models import PartnerSpace
    from organizations.models import Organization
    ilmx_org, created = Organization.objects.get_or_create(name="ilmX", short_name=default_space, defaults={
        'active': True
    })

    PartnerSpace.objects.get_or_create(name=default_space, organization=ilmx_org)


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0005_auto_20211118_0804'),
        ('custom_settings', '0005_partnerspace'),
    ]

    operations = [
        migrations.RunPython(create_default_space_and_organization)
    ]
