# Generated by Django 2.2.16 on 2021-11-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0005_auto_20211118_0804'),
        ('custom_settings', '0005_partnerspace'),
    ]

    operations = [
    ]
