# Generated by Django 2.2.16 on 2021-11-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0005_partnerspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='days_to_unlock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='subsection_to_lock',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
