# Generated by Django 2.2.16 on 2021-11-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0006_auto_20211116_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverviewcontent',
            name='days_to_unlock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
