# Generated by Django 2.2.16 on 2022-04-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0007_courseoverviewcontent_publisher_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='course_banner_image_url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
