# Generated by Django 2.2.16 on 2022-04-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0008_courseoverviewcontent_course_banner_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='days_to_wait_before_reminder',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='last_date_of_reminder',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
