# Generated by Django 2.2.16 on 2022-04-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0008_courseoverviewcontent_course_banner_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='days_till_next_reminder',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='reminder_stop_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
