# Generated by Django 2.2.16 on 2022-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0009_auto_20220425_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='about_page_image_url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
