# Generated by Django 2.2.16 on 2022-09-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0010_courseoverviewcontent_about_page_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='certificate_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='course_for_you_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='instructors_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='offered_by_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='reviews_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
