# Generated by Django 2.2.16 on 2022-10-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0012_courseoverviewcontent_faq_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='group_enrollment_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
