# Generated by Django 2.2.16 on 2022-10-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0012_courseoverviewcontent_faq_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='enrollment_options_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
