# Generated by Django 2.2.16 on 2023-01-31 12:39

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0013_courseoverviewcontent_group_enrollment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCustomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('program_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('program_for_you_html', models.TextField(blank=True, default='')),
                ('instructors_html', models.TextField(blank=True, default='')),
                ('certificate_html', models.TextField(blank=True, default='')),
                ('offered_by_html', models.TextField(blank=True, default='')),
                ('reviews_html', models.TextField(blank=True, default='')),
                ('faq_html', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, max_length=256, null=True)),
                ('group_enrollment_url', models.CharField(blank=True, max_length=256, null=True)),
                ('video_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
