# Generated by Django 2.2.16 on 2023-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0013_courseoverviewcontent_group_enrollment_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseoverviewcontent',
            old_name='about_page_image_url',
            new_name='about_page_banner_color',
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='enrollment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='is_text_color_dark',
            field=models.BooleanField(default=False),
        ),
    ]
