# Generated by Django 2.2.16 on 2023-08-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0014_auto_20230406_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='difficulty_level',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='discount_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
