# Generated by Django 2.2.16 on 2023-12-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0015_auto_20230802_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='seo_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
