# Generated by Django 2.2.16 on 2024-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0016_courseoverviewcontent_seo_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverviewcontent',
            name='seo_words',
            field=models.TextField(blank=True, default=''),
        ),
    ]
