# Generated by Django 2.2.16 on 2024-02-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0017_auto_20240111_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='course_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
