# Generated by Django 2.2.16 on 2024-02-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0018_courseoverviewcontent_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoverviewcontent',
            name='course_description',
        ),
    ]
