# Generated by Django 2.2.16 on 2024-09-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0019_remove_courseoverviewcontent_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='is_professional_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='recommended_courses',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
