# Generated by Django 2.2.16 on 2024-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0020_auto_20240903_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='course_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='custom_language',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
