# Generated by Django 2.2.16 on 2025-06-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0021_auto_20241028_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseoverviewcontent',
            old_name='prerequisites',
            new_name='prerequisites_courses',
        ),
        migrations.AddField(
            model_name='courseoverviewcontent',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
