# Generated by Django 2.2.16 on 2021-06-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overrides', '0002_auto_20210622_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogressstats',
            options={'verbose_name_plural': 'Course Progress Stats'},
        ),
    ]
