# Generated by Django 2.2.16 on 2021-11-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overrides', '0006_auto_20210921_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogressstats',
            name='unlock_subsection_on',
            field=models.DateTimeField(null=True),
        ),
    ]
