# Generated by Django 2.2.16 on 2022-04-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overrides', '0007_courseprogressstats_unlock_subsection_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogressstats',
            name='send_reminder_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courseprogressstats',
            name='unlock_subsection_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
