# Generated by Django 2.2.16 on 2023-02-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_toured',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            "UPDATE auth_userprofile SET has_toured = true WHERE has_toured = false",
        )
    ]
