# Generated by Django 2.2.16 on 2024-09-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_userprofile_has_toured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('u', 'Undergraduate'), ('g', 'Graduate'), ('elp', 'Entry Level Professional'), ('mslp', 'Mid-Senior Level Professional'), ('other', 'Other')], db_index=True, max_length=6, null=True),
        ),
    ]
