# Generated by Django 2.2.16 on 2021-05-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_registration_activation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
    ]
